[agent]
registered = true

[controls]
[controls.power]
[controls.power.inhibit_controls]
disabled = false

[controls.power.power_controls]
disabled = false

[controls.power.screen_lock_controls]
disabled = false

[controls.system]
[controls.system.dbus_commands]
disabled = false

[cpu_vulnerabilities]
disabled = false

[device]
id = '7a3e3f65-0a3f-43dc-958d-06dcd77a7427'
name = 'yugen'

[hass]
apiurl = 'https://hooks.nabu.casa/gAAAAABpc9seZTuOmycqCHab6Xb_cabybF3mW1ActCWKUQsf3FkHrxMqIGldPLaKfHPo6yu6-5p5x4p1pDdZ1Jg0KeVEehIeyxvgQuvVUVCn9kdOqEQQZvE-BJqVSHCxr1Jih83oEqGxxW5B6IG3hOGW8cuoUSOB0wmcwVFViZ1YYuH4emgnBsU='
secret = ''
webhook_id = '12b4bde2fcb6b40eb3516b786356737800e6b16693696ee36e0ad179959f7022'
websocketurl = 'wss://home.zero-two.xyz/api/websocket'

[mqtt]
enabled = true
password = 'mqtt-user'
server = 'tcp://192.168.1.212:1883'
topic_prefix = 'homeassistant'
user = 'mqtt-user'

[registration]
server = 'http://192.168.1.212:8123'
token = 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiI2NDc5YTU0MjZhNDc0YjZjYjNmMGNlZDQ4MTBmMDk4NyIsImlhdCI6MTc2OTIwMDQwMSwiZXhwIjoyMDg0NTYwNDAxfQ.Z-mJ4Iw7LMYkIbNQBmALBd3OhIVAeG0EZsG6m1EKrkY'

[scripts]
disabled = false

[sensors]
[sensors.agent]
[sensors.agent.connection_latency]
disabled = false

[sensors.agent.external_ip]
disabled = false

[sensors.agent.version]
disabled = false

[sensors.batteries]
disabled = false

[sensors.cpu]
[sensors.cpu.frequencies]
disabled = false
update_interval = '30s'

[sensors.cpu.load_averages]
disabled = false

[sensors.cpu.usage]
disabled = false
update_interval = '10s'

[sensors.disk]
[sensors.disk.rates]
disabled = false
update_interval = '5s'

[sensors.disk.usage]
disabled = false
ignored_mounts = ['/tmp/crun', '/run', '/var/lib/containers', '/sys', '/proc']
update_interval = '1m0s'

[sensors.media]
[sensors.media.audio]
disabled = false

[sensors.media.microphone_in_use]
disabled = false

[sensors.media.mpris]
disabled = false

[sensors.media.video]
camera_device = '/dev/video0'
camera_formats = ['Motion-JPEG']
camera_video_height = 640
camera_video_width = 480

[sensors.media.webcam_in_use]
disabled = false

[sensors.memory]
[sensors.memory.oom_events]
disabled = false

[sensors.memory.usage]
disabled = false
update_interval = '1m0s'

[sensors.network]
[sensors.network.connections]
disabled = false
ignored_devices = ['lo', 'veth', 'podman', 'docker', 'vnet']

[sensors.network.links]
disabled = false
ignored_devices = ['lo', 'veth', 'podman', 'docker', 'vnet']

[sensors.network.usage]
disabled = false
ignored_devices = ['lo', 'veth', 'podman', 'docker', 'vnet']
update_interval = '5s'

[sensors.power]
[sensors.power.profile]
disabled = false

[sensors.power.screen_lock]
disabled = false

[sensors.power.state]
disabled = false

[sensors.system]
[sensors.system.hardware_sensors]
disabled = false
update_interval = '1m0s'

[sensors.system.info_sensors]
disabled = false

[sensors.system.last_active]
disabled = false
update_interval = '10s'

[sensors.system.users]
disabled = false
