[config]
reload_apps = true

[config.wallpaper]
command = "awww"
arguments = [ "img", "-t", "fade", "--transition-duration", "0.5", "--transition-step", "255", "--transition-fps", "60", "-f", "Nearest",]
set = true

[templates.hyprland]
input_path = "~/.config/Ax-Shell/config/matugen/templates/hyprland-colors.conf"
output_path = "~/.config/Ax-Shell/config/hypr/colors.conf"

[templates.ax-shell]
input_path = "~/.config/Ax-Shell/config/matugen/templates/ax-shell.css"
output_path = "~/.config/Ax-Shell/styles/colors.css"
post_hook = "fabric-cli exec ax-shell 'app.set_css()' &"

[templates.kitty]
input_path = "~/.config/matugen/kitty-colors.conf"
output_path = "~/.config/kitty/colors.conf"
post_hook = "pkill -SIGUSR1 kitty"

[templates.starship]
input_path = "~/.config/matugen/starship-colors.conf"
output_path = "~/.config/starship.toml"

[templates.vesktop]
input_path = "~/.config/matugen/midnight-discord.css"
output_path = "~/.config/equibop/themes/midnight-discord.css"

[templates.gtk3]
input_path = "~/.config/matugen/gtk-colors.css"
output_path = "~/.config/gtk-3.0/colors.css"
post_hook = "gsettings set org.gnome.desktop.interface gtk-theme \"\"; gsettings set org.gnome.desktop.interface gtk-theme adw-gtk3-{{mode}}"

[templates.gtk4]
input_path = "~/.config/matugen/gtk-colors.css"
output_path = "~/.config/gtk-4.0/colors.css"

[templates.btop]
input_path = "~/.config/matugen/btop.theme"
output_path = "~/.config/btop/themes/matugen.theme"

[templates.qt5ct]
input_path = "~/.config/matugen/qt5ct.conf"
output_path = "~/.config/qt5ct/colors/matugen.conf"

[config.custom_colors.red]
color = "#FF0000"
blend = true

[config.custom_colors.green]
color = "#00FF00"
blend = true

[config.custom_colors.yellow]
color = "#FFFF00"
blend = true

[config.custom_colors.blue]
color = "#0000FF"
blend = true

[config.custom_colors.magenta]
color = "#FF00FF"
blend = true

[config.custom_colors.cyan]
color = "#00FFFF"
blend = true

[config.custom_colors.white]
color = "#FFFFFF"
blend = true
