format = '''
$directory $hostname $fill $git_branch$docker_context$python$golang 
$character'''

palette = 'colors'

[palettes.colors]
mustard = '#af8700' # example
color1 = '#81d4dc'
color2 = '#00363b'
color3 = '#bec8c9'
color4 = '#1a2121'
color5 = '#00363b'
color6 = '#0e1415'
color7 = '#0e1415'
color8 = '#81d4dc'
color9 = '#b7c7ea'

# Prompt symbols 
[character]
success_symbol = "[üç•](color9 bold)"
error_symbol = "[üç•](@{error})"
vicmd_symbol = "[üç•](#f9e2af)"

[directory]
format = "[ÓÇ∂](fg:color1)[Û∞âã](bg:color1 fg:color2)[ÓÇ¥ ](fg:color1 bg:color4)[$path ](fg:color3 bg:color4)[ÓÇ¥ ](fg:color4)"
truncate_to_repo = false
truncation_length = 99
fish_style_pwd_dir_length = 1
use_logical_path=true


[directory.substitutions]
"Documents" = "Û∞àô "
"Downloads" = "ÔÄô "
"Music" = "ÔÄÅ "
"Pictures" = "ÔÄæ "

[git_branch]
format = "[ÓÇ∂](fg:color8)[Ôáì ](bg:color8 fg:color5)[ÓÇ¥](fg:color8 bg:color4)[(bg:color8 fg:color5) $branch](fg:color3 bg:color4)[ÓÇ¥](fg:color4) "

[time]
format = "[ÓÇ∂](fg:color8)[Ôê∫ ](bg:color8 fg:color5)[ÓÇ¥](fg:color8 bg:color4)[(bg:color8 fg:color5) $time](fg:color3 bg:color4)[ÓÇ¥](fg:color4) "
disabled = false
time_format = "%R" # Hour:Minute Format

[python]
format = "[ÓÇ∂](fg:color8)[${symbol}${version}](bg:color8 fg:color5)[ÓÇ¥](fg:color8 bg:color4)[(bg:color8 fg:color5)( ${virtualenv})](fg:color3 bg:color4)[ÓÇ¥](fg:color4) "
symbol = 'üêç'
# pyenv_version_name = true
pyenv_prefix = 'venv'

[docker_context]
format = '[ÓÇ∂](fg:color8)[Óû∞ ](bg:color8 fg:color5)[ÓÇ¥](fg:color8 bg:color4)[(bg:color8 fg:color5) $context](fg:color3 bg:color4)[ÓÇ¥](fg:color4) '

[golang]
format = '[ÓÇ∂](fg:color8)[Û∞üì ](bg:color8 fg:color5)[ÓÇ¥](fg:color8 bg:color4)[(bg:color8 fg:color5) $version](fg:color3 bg:color4)[ÓÇ¥](fg:color4) '

[hostname]
format = '[ÓÇ∂](fg:color8)[Ó¨∫](bg:color8 fg:color5)[ÓÇ¥](fg:color8 bg:color4)[(bg:color8 fg:color5) $hostname](fg:color3 bg:color4)[ÓÇ¥](fg:color4) '

[fill]
symbol = ' '
style = ''
